//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.Branches = new HashSet<Branch>();
        }
    
        public System.Guid Guid { get; set; }
        public int LocationId { get; set; }
        public int Reference { get; set; }
        public string NameSpace { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Woreda { get; set; }
        public string Area { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longtitude { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branches { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
